# Site settings
title: Silicon Valley Insight
email: siliconvalleyinsight@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Silicon Valley Insight - Android, iOS, fullstack web development, and data science.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://siliconvalleyinsight.com" # the base hostname & protocol for your site
twitter_username: SiliconValleyInsight
github_username:  SiliconValleyInsight

# Build settings
markdown: kramdown
